"""15Migration

Revision ID: fccf8351b48c
Revises: 2d5c9970cbc1
Create Date: 2018-09-10 15:03:42.752936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fccf8351b48c'
down_revision = '2d5c9970cbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('comments', 'details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('details', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comments', 'description')
    # ### end Alembic commands ###
